modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="masterblushney"
version="1.0.0"
displayName="MasterBlushney"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="tim73, MCreator"

[[dependencies.masterblushney]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




